"use client";

import { useEffect, useRef, useState, type FormEvent, type ReactNode } from 'react';
import { ArrowDownLeft, ArrowUpRight, ArrowLeft, ArrowRight, Check, CheckCheck, CircleHelp, Clock3, Droplets, FileCheck2, FileText, GraduationCap, HeartHandshake, HeartPulse, LayoutDashboard, Layers3, LockKeyhole, MapPin, Plus, RotateCcw, Search, ShieldCheck, Wallet, X } from 'lucide-react';
import { Sidebar, SidebarProvider, SidebarContent, SidebarFooter, SidebarHeader, SidebarMenu, SidebarMenuItem, SidebarMenuButton, SidebarTrigger, useSidebar } from '@/components/ui/sidebar';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { AlertDialog, AlertDialogContent, AlertDialogHeader, AlertDialogTitle, AlertDialogDescription, AlertDialogFooter, AlertDialogAction, AlertDialogCancel } from '@/components/ui/alert-dialog';
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from '@/components/ui/select';
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Progress } from '@/components/ui/progress';
import { Table, TableHeader, TableHead, TableRow, TableBody, TableCell } from '@/components/ui/table';
import { Toaster } from '@/components/ui/sonner';
import { toast } from 'sonner';
import { z } from 'zod';
import { applyAction, seedLedger, cents, goal, released, balance, type Ledger, type Campaign, type Milestone, type Role, type Action, type Entry } from '@/lib/ledger';

const KEY='aidledger-local-demo-v1';
const num=z.number().int().nonnegative().max(300_000_000);
const milestoneSchema=z.object({id:z.string(),title:z.string().max(100),amount:num.positive(),status:z.enum(['planned','pending','approved','rejected','released']),evidence:z.string().max(1500),review:z.string().max(600)});
const savedSchema=z.object({version:z.literal(1),campaigns:z.array(z.object({id:z.string(),title:z.string().max(80),location:z.string().max(80),category:z.enum(['Medical aid','Clean water','Education']),description:z.string().max(800),raised:num,contributions:num,milestones:z.array(milestoneSchema).length(3)})).max(30),entries:z.array(z.object({id:z.string(),campaignId:z.string(),campaign:z.string(),action:z.string(),detail:z.string(),amount:num,role:z.enum(['Donor','Organizer','Verifier']),time:z.string().datetime()})).max(1500)}).refine(s=>s.campaigns.every(c=>c.raised<=goal(c)&&released(c)<=c.raised&&c.milestones.every((m,i)=>m.status==='planned'||c.milestones.slice(0,i).every(p=>p.status==='released'))));
const fmt=(n:number)=>new Intl.NumberFormat('en-US',{maximumFractionDigits:2}).format(n/100);
const iconFor=(category:string)=>category==='Medical aid'?HeartPulse:category==='Clean water'?Droplets:GraduationCap;
const colorFor=(category:string)=>category==='Medical aid'?'medical':category==='Clean water'?'water':'education';
const statusNames={planned:'Planned',pending:'Awaiting review',approved:'Approved',rejected:'Changes requested',released:'Funds released'};
type View='overview'|'campaigns'|'verification'|'history'|'detail';
type Modal={kind:'create'}|{kind:'donate';campaignId:string}|{kind:'evidence'|'review';campaignId:string;milestoneId:string}|{kind:'entry';entry:Entry}|{kind:'about'}|null;
const nav=[{id:'overview',name:'Overview',icon:LayoutDashboard},{id:'campaigns',name:'Campaigns',icon:HeartHandshake},{id:'verification',name:'Verification',icon:ShieldCheck},{id:'history',name:'Proof history',icon:Layers3}] as const;

function SideNav({view,go,pending,onAbout,onReset}:{view:View;go:(v:View)=>void;pending:number;onAbout:()=>void;onReset:()=>void}){
  const {setOpenMobile}=useSidebar();
  return <Sidebar className="aid-sidebar"><SidebarHeader><button className="brand" onClick={()=>{go('overview');setOpenMobile(false)}} aria-label="AidLedger overview"><span className="brand-icon"><HeartHandshake size={25}/></span><span>AidLedger<span className="brand-sub">EVERY STEP ACCOUNTED FOR</span></span></button></SidebarHeader><SidebarContent><p className="nav-label">WORKSPACE</p><SidebarMenu>{nav.map(n=><SidebarMenuItem key={n.id}><SidebarMenuButton size="lg" isActive={view===n.id||(n.id==='campaigns'&&view==='detail')} onClick={()=>{go(n.id);setOpenMobile(false)}}><n.icon/><span>{n.name}</span>{n.id==='verification'&&pending>0&&<b className="nav-count">{pending}</b>}</SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu><div className="sidebar-note"><div className="note-icon"><ShieldCheck size={21}/></div><strong>Purpose. Proof. Progress.</strong><p>Follow each contribution from funding to a completed milestone.</p><button onClick={onAbout}>How it works <ArrowUpRight size={15}/></button></div></SidebarContent><SidebarFooter><button className="sidebar-link" onClick={onAbout}><CircleHelp size={18}/> About this prototype</button><button className="sidebar-link" onClick={onReset}><RotateCcw size={18}/> Reset local demo</button><div className="sidebar-person"><span className="avatar">AL</span><div><strong>Demo workspace</strong><small>Saved in this browser</small></div><span className="tiny-tag">v1</span></div></SidebarFooter></Sidebar>
}

export default function Home(){
  const [state,setState]=useState<Ledger>(seedLedger);
  const live=useRef(state);
  const [ready,setReady]=useState(false);
  const [role,setRole]=useState<Role>('Donor');
  const roleRef=useRef<Role>(role);
  const [view,setView]=useState<View>('overview');
  const [selected,setSelected]=useState('benin');
  const [query,setQuery]=useState('');
  const [filter,setFilter]=useState('all');
  const [modal,setModal]=useState<Modal>(null);
  const [resetOpen,setResetOpen]=useState(false);
  const [error,setError]=useState('');
  const [saveWarning,setSaveWarning]=useState('');
  const [category,setCategory]=useState<Campaign['category']>('Medical aid');
  const [amount,setAmount]=useState('100');
  const [reviewDecision,setReviewDecision]=useState<'approve'|'reject'>('approve');
  useEffect(()=>{try{const raw=localStorage.getItem(KEY);if(raw){const parsed=savedSchema.safeParse(JSON.parse(raw));if(parsed.success){live.current=parsed.data;setState(parsed.data);}else setSaveWarning('Saved demo data could not be loaded. Sample data is shown; use Reset local demo to replace it.');}}catch{setSaveWarning('Browser storage is unavailable. Changes will last for this visit only.');}setReady(true);},[]);
  function persist(next:Ledger){live.current=next;setState(next);try{localStorage.setItem(KEY,JSON.stringify(next));setSaveWarning('');}catch{setSaveWarning('Changes are visible but could not be saved in this browser.');}}
  function changeRole(next:Role){roleRef.current=next;setRole(next);}
  function act(action:Action):boolean{try{const next=applyAction(live.current,action,roleRef.current);persist(next);setError('');toast.success(next.entries[0].action);return true;}catch(e){const message=e instanceof Error?e.message:'The action could not be completed.';setError(message);toast.error(message);return false;}}
  function go(next:View){setView(next);setQuery('');setFilter('all');setError('');}
  function openCampaign(id:string){setSelected(id);setView('detail');setError('');}
  function openModal(next:Modal){setError('');setAmount('100');setReviewDecision('approve');setModal(next);}
  const allMilestones=state.campaigns.flatMap(c=>c.milestones.map(m=>({c,m})));
  const pending=allMilestones.filter(({m})=>m.status==='pending');
  const total=state.campaigns.reduce((s,c)=>s+c.raised,0),out=state.campaigns.reduce((s,c)=>s+released(c),0);
  const approvedCount=allMilestones.filter(({m})=>['approved','released'].includes(m.status)).length;
  const current=state.campaigns.find(c=>c.id===selected)??state.campaigns[0];
  const modalCampaign=modal&&'campaignId' in modal?state.campaigns.find(c=>c.id===modal.campaignId):undefined;
  const modalMilestone=modal&&'milestoneId' in modal?modalCampaign?.milestones.find(m=>m.id===modal.milestoneId):undefined;
  const campaignList=state.campaigns.filter(c=>(c.title+' '+c.location).toLowerCase().includes(query.toLowerCase())&&(filter==='all'||(filter==='funding'&&c.raised<goal(c))||(filter==='review'&&c.milestones.some(m=>m.status==='pending'))||(filter==='complete'&&released(c)===goal(c))));
  useEffect(()=>{
    type Context={registerTool:(tool:unknown,options:{signal:AbortSignal})=>void|Promise<void>};
    const context=(document as Document&{modelContext?:Context}).modelContext;
    if(!context?.registerTool)return;
    const lifecycle=new AbortController();
    const register=(tool:unknown)=>{try{void Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}};
    register({name:'read_aidledger_demo',description:'Read fictional campaign balances and milestones in the local AidLedger demo. No real funds or on-chain records.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:()=>({mode:'local demo',campaigns:live.current.campaigns})});
    register({name:'open_aidledger_campaign',description:'Navigate to an existing campaign detail page. Does not contribute or release any funds.',inputSchema:{type:'object',properties:{campaignId:{type:'string'}},required:['campaignId'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:async(input:unknown)=>{const parsed=z.object({campaignId:z.string()}).strict().parse(input);if(!live.current.campaigns.some(c=>c.id===parsed.campaignId))throw new Error('Campaign not found.');openCampaign(parsed.campaignId);await new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve())));return{openedCampaignId:parsed.campaignId};}});
    return()=>lifecycle.abort();
  },[]);

  function submitForm(e:FormEvent<HTMLFormElement>){
    e.preventDefault();const form=new FormData(e.currentTarget);
    try{
      let action:Action;
      if(modal?.kind==='create')action={type:'create',title:String(form.get('title')??''),location:String(form.get('location')??''),description:String(form.get('description')??''),category,milestones:[0,1,2].map(i=>({title:String(form.get('milestone'+i)??''),amount:cents(String(form.get('budget'+i)??''))}))};
      else if(modal?.kind==='donate')action={type:'donate',campaignId:modal.campaignId,amount:cents(amount)};
      else if(modal?.kind==='evidence')action={type:'submit',campaignId:modal.campaignId,milestoneId:modal.milestoneId,evidence:String(form.get('evidence')??'')};
      else if(modal?.kind==='review')action={type:'review',campaignId:modal.campaignId,milestoneId:modal.milestoneId,approve:reviewDecision==='approve',review:String(form.get('review')??'')};
      else return;
      if(act(action)){setModal(null);if(action.type==='create')openCampaign(live.current.campaigns[0].id);}
    }catch(e){setError(e instanceof Error?e.message:'Please check the form.');}
  }

  function Card({c}:{c:Campaign}){const Icon=iconFor(c.category);const done=c.milestones.filter(m=>m.status==='released').length;return <article className="campaign-card"><div className="campaign-top"><span className={'category-icon '+colorFor(c.category)}><Icon size={23}/></span><span className={'badge '+(done===3?'released':c.milestones.some(m=>m.status==='pending')?'pending':'neutral')}>{done===3?'Completed':c.milestones.some(m=>m.status==='pending')?'In review':'Active campaign'}</span></div><span className="eyebrow">{c.category}</span><h3><button onClick={()=>openCampaign(c.id)}>{c.title}</button></h3><p className="location"><MapPin size={14}/>{c.location}</p><div className="funding-line"><strong>{fmt(c.raised)} <span>credits</span></strong><span>{Math.round(c.raised/goal(c)*100)}%</span></div><Progress aria-label={`${c.title} funding`} value={c.raised/goal(c)*100}/><p className="goal-label">of {fmt(goal(c))} demo credits goal</p><div className="card-footer"><span><ShieldCheck size={16}/>{done}/3 milestones released</span><button aria-label={`View ${c.title}`} onClick={()=>openCampaign(c.id)}><ArrowUpRight size={20}/></button></div></article>}
  function Activity({entries,full=false}:{entries:Entry[];full?:boolean}){if(!entries.length)return <Empty text="No activity yet. Actions you complete will appear here."/>;return full?<div className="table-wrap"><Table><TableHeader><TableRow><TableHead>Activity</TableHead><TableHead>Campaign</TableHead><TableHead>Demo amount</TableHead><TableHead>Role</TableHead><TableHead>Time (UTC)</TableHead><TableHead><span className="sr-only">Details</span></TableHead></TableRow></TableHeader><TableBody>{entries.map(e=><TableRow key={e.id}><TableCell><strong>{e.action}</strong></TableCell><TableCell>{e.campaign}</TableCell><TableCell>{e.amount?fmt(e.amount)+' credits':'—'}</TableCell><TableCell>{e.role}</TableCell><TableCell>{new Date(e.time).toISOString().replace('T',' ').slice(0,16)}</TableCell><TableCell><button className="text-button" onClick={()=>openModal({kind:'entry',entry:e})}>Details</button></TableCell></TableRow>)}</TableBody></Table></div>:<div className="activity-list">{entries.map(e=><button className="activity-item" key={e.id} onClick={()=>openModal({kind:'entry',entry:e})}><span className={'activity-icon '+(e.action.includes('released')?'green':'')} >{e.action.includes('released')?<ArrowUpRight size={18}/>:e.action.includes('approved')?<ShieldCheck size={18}/>:<FileText size={18}/>}</span><span className="activity-copy"><strong>{e.action}</strong><small>{e.campaign}</small></span><span className="activity-meta">{e.amount?fmt(e.amount)+' cr':new Date(e.time).toLocaleDateString('en-GB',{day:'numeric',month:'short',timeZone:'UTC'})}<ArrowUpRight size={14}/></span></button>)}</div>}
  function ReviewCard({c,m}:{c:Campaign;m:Milestone}){return <article className="review-card"><div className="row between"><span className="badge pending"><Clock3 size={13}/>Awaiting review</span><span className="mono">{fmt(m.amount)} credits</span></div><h3>{m.title}</h3><button className="text-button" onClick={()=>openCampaign(c.id)}>{c.title} <ArrowUpRight size={14}/></button><p className="evidence-excerpt">{m.evidence}</p><button className="btn primary full" disabled={role!=='Verifier'} onClick={()=>openModal({kind:'review',campaignId:c.id,milestoneId:m.id})}>Review evidence <ArrowRight size={16}/></button></article>}
  function MilestoneRow({c,m,i}:{c:Campaign;m:Milestone;i:number}){const unlocked=c.milestones.slice(0,i).every(p=>p.status==='released');return <div className={'milestone-row '+m.status}><span className="step-number">{m.status==='released'?<Check size={19}/>:String(i+1).padStart(2,'0')}</span><div className="milestone-body"><div className="row between"><h3>{m.title}</h3><strong>{fmt(m.amount)} <small>credits</small></strong></div><span className={'badge '+m.status}>{statusNames[m.status]}</span>{m.evidence&&<details><summary>View submitted evidence</summary><p>{m.evidence}</p>{m.review&&<><strong>Verifier note</strong><p>{m.review}</p></>}</details>}<div className="milestone-action">{!unlocked?<span className="muted row"><LockKeyhole size={14}/>Complete the previous milestone first</span>:m.status==='planned'||m.status==='rejected'?role==='Organizer'?<button className="btn secondary small" onClick={()=>openModal({kind:'evidence',campaignId:c.id,milestoneId:m.id})}><FileText size={16}/>{m.status==='rejected'?'Resubmit evidence':'Submit evidence'}</button>:<span className="muted">Organizer can submit evidence.</span>:m.status==='pending'?role==='Verifier'?<button className="btn primary small" onClick={()=>openModal({kind:'review',campaignId:c.id,milestoneId:m.id})}>Review evidence <ArrowRight size={15}/></button>:<span className="muted">Waiting for verifier review.</span>:m.status==='approved'?<><button className="btn primary small" disabled={role!=='Organizer'||balance(c)<m.amount} onClick={()=>act({type:'release',campaignId:c.id,milestoneId:m.id})}><ArrowUpRight size={16}/>Release demo funds</button>{balance(c)<m.amount?<p className="muted">Needs {fmt(m.amount-balance(c))} more demo credits.</p>:role!=='Organizer'&&<p className="muted">Switch to Organizer to release.</p>}</>:<span className="row success"><CheckCheck size={16}/>Release recorded in proof history</span>}</div></div></div>}

  return <SidebarProvider style={{'--sidebar-width':'244px'} as React.CSSProperties}><Toaster richColors position="bottom-right"/><SideNav view={view} go={go} pending={pending.length} onAbout={()=>openModal({kind:'about'})} onReset={()=>setResetOpen(true)}/><main className="main-shell"><header className="topbar"><div className="row"><SidebarTrigger className="mobile-trigger"/><span className="breadcrumb">Workspace <span>/</span> <strong>{view==='detail'?'Campaign details':nav.find(n=>n.id===view)?.name}</strong></span></div><div className="topbar-right"><span className="demo-pill"><span/>Local demo</span><div className="role-picker"><span>Demo role</span><Select value={role} onValueChange={v=>changeRole(v as Role)}><SelectTrigger aria-label="Demo role"><SelectValue/></SelectTrigger><SelectContent>{(['Donor','Organizer','Verifier'] as Role[]).map(r=><SelectItem key={r} value={r}>{r}</SelectItem>)}</SelectContent></Select></div><span className="avatar header-avatar">AL</span></div></header><div className="content">{saveWarning&&<div role="status" className="warning">{saveWarning}</div>}{!ready?<div className="loading" role="status">Opening your demo workspace…</div>:<>
      {view==='overview'&&<><div className="page-heading"><div><p className="eyebrow">THE BIG PICTURE</p><h1>Good intentions. Visible impact.</h1><p>Track the funding. See the proof. Follow the progress.</p></div><button className="btn primary" onClick={()=>{changeRole('Organizer');openModal({kind:'create'});}}><Plus size={18}/>Create campaign</button></div><div className="stats"><Stat title="Total raised" value={fmt(total)} note="demo credits" icon={<Wallet size={20}/>}/><Stat title="Funds released" value={fmt(out)} note="demo credits" icon={<ArrowUpRight size={20}/>}/><Stat title="Awaiting review" value={String(pending.length).padStart(2,'0')} note="milestone evidence" icon={<Clock3 size={20}/>} warm/><Stat title="Approved milestones" value={String(approvedCount).padStart(2,'0')} note={`of ${allMilestones.length} total milestones`} icon={<ShieldCheck size={20}/>}/></div><div className="dashboard-grid"><section><div className="section-heading"><h2>Active campaigns <span className="count">{state.campaigns.filter(c=>released(c)<goal(c)).length}</span></h2><button className="text-button" onClick={()=>go('campaigns')}>View all <ArrowRight size={15}/></button></div><div className="campaign-grid">{state.campaigns.filter(c=>released(c)<goal(c)).slice(0,4).map(c=><Card key={c.id} c={c}/>)}</div><section className="panel activity-panel"><div className="section-heading"><h2>Recent activity</h2><button className="text-button" onClick={()=>go('history')}>Full history <ArrowRight size={15}/></button></div><Activity entries={state.entries.slice(0,4)}/></section></section><aside className="right-column"><section className="balance-card"><span className="balance-icon"><LockKeyhole size={22}/></span><p>Awaiting milestone release</p><strong>{fmt(total-out)} <span>credits</span></strong><div className="balance-track"><span style={{width:(total?out/total*100:0)+'%'}}/></div><div className="balance-legend"><span><i/>Released</span><span>{total?Math.round(out/total*100):0}% of funds</span></div><p className="balance-foot">Demo funds remain in the simulated balance until a milestone is approved.</p></section><section className="review-panel"><div className="section-heading"><h2>Needs attention</h2><span className="count amber">{pending.length}</span></div>{pending.length?pending.slice(0,2).map(({c,m})=><div key={m.id} className="attention-item"><span className="mini-label">MILESTONE REVIEW</span><h3>{m.title}</h3><p>{c.title}</p><button className="btn secondary full" onClick={()=>{changeRole('Verifier');go('verification');}}>Open verification <ArrowRight size={16}/></button></div>):<Empty text="All caught up. No evidence is waiting for review."/>}</section><div className="trust-note"><ShieldCheck size={19}/><p>Every release has a reason.<br/><strong>Make it a verifiable one.</strong></p></div></aside></div></>}
      {view==='campaigns'&&<><div className="page-heading"><div><p className="eyebrow">FUND SOMETHING MEANINGFUL</p><h1>Campaigns</h1><p>Explore the budgets and milestones behind each project.</p></div><button className="btn primary" onClick={()=>{changeRole('Organizer');openModal({kind:'create'});}}><Plus size={18}/>Create campaign</button></div><div className="filter-bar"><Tabs value={filter} onValueChange={setFilter}><TabsList><TabsTrigger value="all">All campaigns</TabsTrigger><TabsTrigger value="funding">Funding</TabsTrigger><TabsTrigger value="review">In review</TabsTrigger><TabsTrigger value="complete">Completed</TabsTrigger></TabsList></Tabs><label className="search"><Search size={17}/><input aria-label="Search campaigns" placeholder="Search campaigns" value={query} onChange={e=>setQuery(e.target.value)}/></label></div>{campaignList.length?<div className="campaign-grid all-campaigns">{campaignList.map(c=><Card key={c.id} c={c}/>)}</div>:<Empty text="No campaigns match your search or filter."/>}</>}
      {view==='verification'&&<><div className="page-heading"><div><p className="eyebrow">ACCOUNTABILITY IN ACTION</p><h1>Verification queue</h1><p>Review the evidence behind every requested release.</p></div><span className="badge pending">{pending.length} awaiting review</span></div>{role!=='Verifier'&&<div className="role-notice"><ShieldCheck size={21}/><p>Switch to the simulated verifier role to approve evidence or request changes.</p><button className="btn secondary small" onClick={()=>changeRole('Verifier')}>Use verifier role</button></div>}<div className="review-grid">{pending.map(({c,m})=><ReviewCard key={m.id} c={c} m={m}/>)}</div>{!pending.length&&<Empty text="No evidence is waiting for review. As Organizer, submit evidence from a campaign’s milestone timeline."/>}<div className="fine-print">Verifier roles are simulated for this prototype. Approval records a demo decision; it does not establish real-world proof.</div></>}
      {view==='history'&&<><div className="page-heading"><div><p className="eyebrow">THE RECORD BEHIND THE IMPACT</p><h1>Proof history</h1><p>Contributions, evidence, decisions, and releases in one place.</p></div><span className="badge neutral">{state.entries.length} local records</span></div><div className="history-controls"><Select value={filter} onValueChange={setFilter}><SelectTrigger aria-label="Filter history by campaign"><SelectValue placeholder="All campaigns"/></SelectTrigger><SelectContent><SelectItem value="all">All campaigns</SelectItem>{state.campaigns.map(c=><SelectItem key={c.id} value={c.id}>{c.title}</SelectItem>)}</SelectContent></Select><p className="muted">Local activity log · not an immutable or on-chain record</p></div><section className="panel"><Activity full entries={state.entries.filter(e=>filter==='all'||e.campaignId===filter)}/></section></>}
      {view==='detail'&&current&&<><button className="back-button" onClick={()=>go('campaigns')}><ArrowLeft size={16}/>All campaigns</button><div className="page-heading detail-heading"><div><span className={'badge '+colorFor(current.category)}>{current.category}</span><h1>{current.title}</h1><p className="location"><MapPin size={16}/>{current.location}<span className="dot-separator">·</span>Fictional demo campaign</p></div></div><div className="detail-grid"><div><section className="panel about-campaign"><h2>About this campaign</h2><p>{current.description}</p></section><section className="panel milestones-panel"><div className="section-heading"><h2>Milestone timeline</h2><span className="muted">{current.milestones.filter(m=>m.status==='released').length}/3 released</span></div>{current.milestones.map((m,i)=><MilestoneRow key={m.id} c={current} m={m} i={i}/>)}</section><section className="panel activity-panel"><div className="section-heading"><h2>Campaign activity</h2></div><Activity entries={state.entries.filter(e=>e.campaignId===current.id).slice(0,5)}/></section></div><aside><section className="panel contribution-card"><p className="eyebrow">CAMPAIGN FUNDING</p><div className="detail-total">{fmt(current.raised)} <span>credits</span></div><p className="muted">of {fmt(goal(current))} demo credits</p><Progress aria-label="Campaign funding" value={current.raised/goal(current)*100}/><div className="row between"><span>{Math.round(current.raised/goal(current)*100)}% funded</span><span>{current.contributions} contributions</span></div><dl className="fund-breakdown"><div><dt><LockKeyhole size={16}/>Awaiting release</dt><dd>{fmt(balance(current))}</dd></div><div><dt><ArrowUpRight size={16}/>Released</dt><dd>{fmt(released(current))}</dd></div></dl><button className="btn primary full" disabled={current.raised>=goal(current)} onClick={()=>{changeRole('Donor');openModal({kind:'donate',campaignId:current.id});}}><Plus size={17}/>{current.raised>=goal(current)?'Funding goal reached':'Add demo funds'}</button><p className="caption">Simulated credits only. No wallet or payment required.</p></section><section className="flow-note"><h3>From intention to impact</h3><ol><li><Wallet size={17}/><span>Contribute demo funds</span></li><li><FileCheck2 size={17}/><span>Submit and review evidence</span></li><li><CheckCheck size={17}/><span>Release the milestone budget</span></li></ol></section></aside></div></>}
    </>}<footer className="page-footer"><span><HeartHandshake size={16}/>AidLedger</span><p>Transparent aid, one milestone at a time.</p><span>Local prototype · no real funds</span></footer></div></main>
    <Dialog open={!!modal} onOpenChange={open=>{if(!open)setModal(null)}}><DialogContent className="aid-dialog"><DialogHeader><DialogTitle>{modal?.kind==='create'?'Create a campaign':modal?.kind==='donate'?'Add demo funds':modal?.kind==='evidence'?'Submit milestone evidence':modal?.kind==='review'?'Review milestone evidence':modal?.kind==='entry'?'Activity details':'How AidLedger works'}</DialogTitle><DialogDescription>{modalCampaign?modalCampaign.title:modal?.kind==='create'?'Set a clear goal with three accountable milestones.':'A local prototype for transparent aid funding.'}</DialogDescription></DialogHeader>
      {modal?.kind==='about'?<div className="about-modal"><p>AidLedger makes campaign budgets and milestone decisions visible. Try the same campaign from three perspectives:</p><ol><li><strong>Donor</strong> adds fictional credits to a campaign.</li><li><strong>Organizer</strong> submits written evidence for the next milestone.</li><li><strong>Verifier</strong> reviews the evidence and approves it or requests changes.</li><li><strong>Organizer</strong> releases the approved amount when enough credits are available.</li></ol><div className="warning">This version uses editable browser storage and simulated roles. It has no wallet connection, smart contract, shared database, or real-world verification. Do not enter personal or patient information.</div><p>Changes stay in this browser. Reset restores the fictional sample campaigns.</p></div>:modal?.kind==='entry'?<div className="entry-details"><span className="badge neutral">Local demo record</span><h3>{modal.entry.action}</h3><p>{modal.entry.campaign}</p><dl><div><dt>Demo amount</dt><dd>{modal.entry.amount?fmt(modal.entry.amount)+' credits':'—'}</dd></div><div><dt>Simulated role</dt><dd>{modal.entry.role}</dd></div><div><dt>Time (UTC)</dt><dd>{new Date(modal.entry.time).toISOString().replace('T',' ').slice(0,19)}</dd></div></dl><p className="evidence-box">{modal.entry.detail}</p><label>Local record ID<code>{modal.entry.id}</code></label></div>:<form onSubmit={submitForm} className="aid-form">
      {modal?.kind==='create'&&<><label>Campaign name<input name="title" required minLength={4} maxLength={80} placeholder="e.g. Community care supplies"/></label><div className="form-grid"><label>Location<input name="location" required minLength={2} maxLength={80} placeholder="City, country"/></label><label>Category<Select value={category} onValueChange={v=>setCategory(v as Campaign['category'])}><SelectTrigger aria-label="Campaign category"><SelectValue/></SelectTrigger><SelectContent>{['Medical aid','Clean water','Education'].map(c=><SelectItem value={c} key={c}>{c}</SelectItem>)}</SelectContent></Select></label></div><label>What will this campaign achieve?<textarea name="description" required minLength={20} maxLength={800} rows={3} placeholder="Use a fictional scenario with a clear, measurable outcome."/></label><h3>Three milestone budgets</h3>{[0,1,2].map(i=><div className="milestone-form" key={i}><span>{i+1}</span><label>Milestone {i+1}<input name={'milestone'+i} aria-label={`Milestone ${i+1} title`} required minLength={3} maxLength={100} placeholder={['Purchase supplies','Deliver support','Final handover'][i]}/></label><label>Demo credits<input name={'budget'+i} aria-label={`Milestone ${i+1} budget`} required type="number" min="0.01" max="1000000" step="0.01" placeholder="1,000"/></label></div>)}<p className="caption">The funding goal equals the sum of these three budgets.</p></>}
      {modal?.kind==='donate'&&modalCampaign&&<><div className="donation-summary"><Wallet size={24}/><div><strong>{fmt(goal(modalCampaign)-modalCampaign.raised)} credits</strong><p>remaining to reach the goal</p></div></div><label>Amount in demo credits<input name="amount" aria-label="Amount in demo credits" type="number" min="0.01" max={(goal(modalCampaign)-modalCampaign.raised)/100} step="0.01" required value={amount} onChange={e=>setAmount(e.target.value)}/></label><div className="quick-amounts">{[100,250,500].map(n=><button type="button" key={n} disabled={n*100>goal(modalCampaign)-modalCampaign.raised} onClick={()=>setAmount(String(n))}>{n} credits</button>)}</div><p className="caption">This adds fictional credits. No money changes hands.</p></>}
      {modal?.kind==='evidence'&&modalMilestone&&<><h3>{modalMilestone.title}</h3>{modalMilestone.review&&<p className="warning">Verifier feedback: {modalMilestone.review}</p>}<label>Evidence summary<textarea name="evidence" required minLength={20} maxLength={1500} rows={6} defaultValue={modalMilestone.evidence} placeholder="Describe the fictional work completed, the budget used, and what a verifier should check."/></label><p className="caption">Use sample information only. This prototype stores text locally; it does not upload documents.</p></>}
      {modal?.kind==='review'&&modalMilestone&&<><div className="row between"><h3>{modalMilestone.title}</h3><strong>{fmt(modalMilestone.amount)} credits</strong></div><div className="evidence-box">{modalMilestone.evidence}</div><label>Decision<Select value={reviewDecision} onValueChange={v=>setReviewDecision(v as 'approve'|'reject')}><SelectTrigger aria-label="Review decision"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="approve">Approve evidence</SelectItem><SelectItem value="reject">Request changes</SelectItem></SelectContent></Select></label><label>Review note<textarea name="review" minLength={10} maxLength={600} required rows={3} placeholder="Explain the checks you made or what needs to change."/></label><p className="caption">Approval permits a later demo release. It does not release funds immediately.</p></>}
      {error&&<p role="alert" className="form-error">{error}</p>}<button className="btn primary full" type="submit">{modal?.kind==='create'?'Create demo campaign':modal?.kind==='donate'?'Confirm demo contribution':modal?.kind==='evidence'?'Send for review':'Save review decision'}<ArrowRight size={16}/></button></form>}
    </DialogContent></Dialog><AlertDialog open={resetOpen} onOpenChange={setResetOpen}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Reset this local demo?</AlertDialogTitle><AlertDialogDescription>Your campaigns, contributions, evidence, and reviews in this browser will be replaced with the sample data.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Keep my changes</AlertDialogCancel><AlertDialogAction onClick={()=>{persist(seedLedger());changeRole('Donor');go('overview');setModal(null);toast.success('Sample demo restored');}}>Reset demo</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></SidebarProvider>
}
function Stat({title,value,note,icon,warm=false}:{title:string;value:string;note:string;icon:ReactNode;warm?:boolean}){return <section className={'stat-card '+(warm?'warm':'')}><div className="row between"><p>{title}</p><span className="stat-icon">{icon}</span></div><strong>{value}</strong><span>{note}</span></section>}
function Empty({text}:{text:string}){return <div className="empty-state"><FileCheck2 size={28}/><p>{text}</p></div>}
